### ISSUE TITLE
Input Field Not Cleared

### ISSUE THREAD

**Issue by mavines** [oxalorg/4ever-clojure#37] opened 2021-07-14 14:13 UTC
When you answer a question and then use the link to go to the next question, your previous answer stays in the answer box. 
Even after deleting it and filling in the correct one, the answer isn't accepted.
Refreshing the browser fixed it. 
I'm on Firefox.

**Comment by oxalorg** [comment] 2021-07-15 11:12
Thank you this is a duplicate of #31 , but leaving this issue open as the scope of that issue is too big and others will likely have a similar issue until that is fixed.

**Closed as completed** 2022-01-27 20:03 UTC
Labels: bug, duplicate
